#include "Arms.h"
#include "../RobotMap.h"
#include <Robot.h>

Arms::Arms() : Subsystem("Arms") {
    x_AXIS_LEFT_SOLENOID = RobotMap::armsX_AXIS_LEFT_SOLENOID;
    x_AXIS_RIGHT_SOLENOID = RobotMap::armsX_AXIS_RIGHT_SOLENOID;
    y_AXIS_LEFT_SOLENOID = RobotMap::armsY_AXIS_LEFT_SOLENOID;
    y_AXIS_RIGHT_SOLENOID = RobotMap::armsY_AXIS_RIGHT_SOLENOID;
}

void Arms::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Arms::Periodic() {
    // Put code here to be run every loop

}


// Put methods for controlling this subsystem
// here. Call these from Commands.

