#ifndef ARMS_H
#define ARMS_H

#include <Robot.h>
#include "Commands/Subsystem.h"
#include "WPILib.h"


class Arms: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities

	shared_ptr<Solenoid> x_AXIS_LEFT_SOLENOID;
	shared_ptr<Solenoid> x_AXIS_RIGHT_SOLENOID;
	shared_ptr<Solenoid> y_AXIS_LEFT_SOLENOID;
	shared_ptr<Solenoid> y_AXIS_RIGHT_SOLENOID;

public:
	Arms();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
