#include "Arms.h"
#include "../RobotMap.h"
#include "../Robot.h"

Arms::Arms() : Subsystem("Arms") {

}

void Arms::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Arms::Periodic() {
    // Put code here to be run every loop

}

void Arms::open() {
	x_AXIS_SOLENOID->Set(false);	//needs to be tested
}

void Arms::close() {
	x_AXIS_SOLENOID->Set(true);	//needs to be tested
}
// Put methods for controlling this subsystem
// here. Call these from Commands.

bool Arms::isOpen() {
	return is_open;
}
