// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CONVEYORBELTS_H
#define CONVEYORBELTS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class ConveyorBelts: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<WPI_VictorSPX> mOTOR_LEFT_CON_BELT;
	std::shared_ptr<WPI_VictorSPX> mOTOR_RIGHT_CON_BELT;
	std::shared_ptr<frc::DifferentialDrive> differentialDrive2;
	std::shared_ptr<frc::DigitalInput> leftConBeltLS;
	std::shared_ptr<frc::DigitalInput> rightConBeltLS;
	std::shared_ptr<frc::SpeedController> leftConBeltSpeedController;
	std::shared_ptr<frc::SpeedController> rightConBeltSpeedController;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	ConveyorBelts();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
