// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LIFT_H
#define LIFT_H

#include "Commands/PIDSubsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Lift: public frc::PIDSubsystem {
 public:
	std::shared_ptr<PWMTalonSRX> MOTOR_LIFT;
	std::shared_ptr<frc::SpeedController> liftSpeedController;
	std::shared_ptr<frc::DigitalInput> topLS;
	std::shared_ptr<frc::DigitalInput> bottomLS;
	std::shared_ptr<frc::AnalogPotentiometer> stringPot;

	Lift();
	double ReturnPIDInput() override;
	void UsePIDOutput(double output) override;
	void InitDefaultCommand() override;
};

#endif
