#ifndef SRC_COMMANDS_AUTOPLAYS_CROSSAUTOLINE_H_
#define SRC_COMMANDS_AUTOPLAYS_CROSSAUTOLINE_H_

class crossAutoLine {
public:
	crossAutoLine();
};

#endif /* SRC_COMMANDS_AUTOPLAYS_CROSSAUTOLINE_H_ */
