#include "OI.h"
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/closePiston.h"
#include "Commands/deployRung.h"
#include "Commands/holdClimber.h"
#include "Commands/moveIntakeOut.h"
#include "Commands/moveLeft.h"
#include "Commands/moveLift.h"
#include "Commands/moveRight.h"
#include "Commands/movetoScaleBottom.h"
#include "Commands/movetoScaleNeutral.h"
#include "Commands/movetoScaleTop.h"
#include "Commands/movetoSwitchTop.h"
#include "Commands/openPiston.h"
#include "Commands/pickUpCube.h"
#include "Commands/releaseCube.h"
#include "Commands/rotateCube.h"
#include "Commands/stopIntake.h"


OI::OI() {
    // Process operator interface input here.
    joystick1.reset(new frc::Joystick(4));
    
    hold.reset(new frc::JoystickButton(joystick1.get(), 1));
    hold->WhenPressed(new holdClimber(0));
    scaleNeutral.reset(new frc::JoystickButton(joystick1.get(), 1));
    scaleNeutral->WhenPressed(new movetoScaleNeutral(0));
    switchTop.reset(new frc::JoystickButton(joystick1.get(), 1));
    switchTop->WhenPressed(new movetoSwitchTop(0));
    scaleBottom.reset(new frc::JoystickButton(joystick1.get(), 1));
    scaleBottom->WhenPressed(new movetoScaleBottom(0));
    joy_left_con_belt.reset(new frc::JoystickButton(joystick1.get(), 1));
    joy_left_con_belt->WhenPressed(new moveIntakeOut());
    rung.reset(new frc::JoystickButton(joystick1.get(), 1));
    rung->WhenPressed(new deployRung());
    closePistonButton.reset(new frc::JoystickButton(joystick1.get(), 1));
    closePistonButton->WhenPressed(new closePiston());
    openPistonButton.reset(new frc::JoystickButton(joystick1.get(), 1));
    openPistonButton->WhenPressed(new openPiston());
    scaleTop.reset(new frc::JoystickButton(joystick1.get(), 1));
    scaleTop->WhenPressed(new movetoScaleTop(0));
    joy_con_belt_left.reset(new frc::Joystick(5));
    
    joy_lift.reset(new frc::Joystick(3));
    
    joy_climber.reset(new frc::Joystick(2));
    
    joy_right.reset(new frc::Joystick(1));
    
    joy_left.reset(new frc::Joystick(0));
    

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("holdClimber", new holdClimber());
    frc::SmartDashboard::PutData("rotateCube", new rotateCube());
    frc::SmartDashboard::PutData("releaseCube", new releaseCube());
    frc::SmartDashboard::PutData("pickUpCube", new pickUpCube());
    frc::SmartDashboard::PutData("stopIntake", new stopIntake());
    frc::SmartDashboard::PutData("moveLift", new moveLift());
    frc::SmartDashboard::PutData("moveRight", new moveRight());
    frc::SmartDashboard::PutData("moveLeft", new moveLeft());
    frc::SmartDashboard::PutData("movetoScaleTop", new movetoScaleTop());
    frc::SmartDashboard::PutData("movetoScaleNeutral", new movetoScaleNeutral());
    frc::SmartDashboard::PutData("movetoSwitchTop", new movetoSwitchTop());
    frc::SmartDashboard::PutData("movetoScaleBottom", new movetoScaleBottom());
    frc::SmartDashboard::PutData("moveIntakeOut", new moveIntakeOut());
    frc::SmartDashboard::PutData("closePiston", new closePiston());
    frc::SmartDashboard::PutData("openPiston", new openPiston());
    frc::SmartDashboard::PutData("deployRung", new deployRung());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getjoy_left() {
   return joy_left;
}

std::shared_ptr<frc::Joystick> OI::getjoy_right() {
   return joy_right;
}

std::shared_ptr<frc::Joystick> OI::getjoy_climber() {
   return joy_climber;
}

std::shared_ptr<frc::Joystick> OI::getjoy_lift() {
   return joy_lift;
}

std::shared_ptr<frc::Joystick> OI::getjoy_con_belt_left() {
   return joy_con_belt_left;
}

std::shared_ptr<frc::Joystick> OI::getJoystick1() {
   return joystick1;
}

