// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

#include "WPILib.h"
#include "ctre/Phoenix.h"

class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<frc::SpeedController> mobilityRLspeedController;
	static std::shared_ptr<WPI_TalonSRX> mobilityREAR_LEFT_MOTOR;
	static std::shared_ptr<frc::SpeedController> mobilityFLspeedController;
	static std::shared_ptr<WPI_TalonSRX> mobilityFRONT_LEFT_MOTOR;
	static std::shared_ptr<frc::SpeedControllerGroup> mobilityleftSpeedController;
	static std::shared_ptr<frc::SpeedController> mobilityRRspeedController;
	static std::shared_ptr<WPI_TalonSRX> mobilityREAR_RIGHT_MOTOR;
	static std::shared_ptr<frc::SpeedController> mobilityFRspeedController;
	static std::shared_ptr<WPI_TalonSRX> mobilityFRONT_RIGHT_MOTOR;
	static std::shared_ptr<frc::SpeedControllerGroup> mobilityrightSpeedController;
	static std::shared_ptr<frc::RobotDrive> mobilityRobotDrive41;
	static std::shared_ptr<frc::Encoder> mobilityleftEncoder;
	static std::shared_ptr<frc::Encoder> mobilityrightEncoder;

	static std::shared_ptr<WPI_TalonSRX> liftMOTOR_LIFT;
	static std::shared_ptr<frc::SpeedController> liftliftSpeedController;
	static std::shared_ptr<frc::DigitalInput> lifttopLS;
	static std::shared_ptr<frc::DigitalInput> liftbottomLS;
	static std::shared_ptr<frc::AnalogPotentiometer> liftStringPot;

	static std::shared_ptr<frc::Solenoid> armsX_AXIS_LEFT_SOLENOID;
	static std::shared_ptr<frc::Solenoid> armsX_AXIS_RIGHT_SOLENOID;
	static std::shared_ptr<frc::Solenoid> armsY_AXIS_LEFT_SOLENOID;
	static std::shared_ptr<frc::Solenoid> armsY_AXIS_RIGHT_SOLENOID;

	static std::shared_ptr<frc::Solenoid> rungBACK_BAR_SOLENOID;

	static std::shared_ptr<WPI_VictorSPX> climberMOTOR_CLIMBER;
	static std::shared_ptr<frc::DigitalInput> climberclimberTopLS;
	static std::shared_ptr<frc::DigitalInput> climberclimberBottomLS;
	static std::shared_ptr<frc::SpeedController> climberclimberSpeedController;
	static std::shared_ptr<frc::AnalogPotentiometer> climberSTRING_POT;

	static std::shared_ptr<frc::DigitalOutput> lEDLightsLED;

	static std::shared_ptr<WPI_VictorSPX> conveyorBeltsMOTOR_LEFT_CON_BELT;
	static std::shared_ptr<WPI_VictorSPX> conveyorBeltsMOTOR_RIGHT_CON_BELT;
	static std::shared_ptr<frc::DifferentialDrive> conveyorBeltsDifferentialDrive2;
	static std::shared_ptr<frc::DigitalInput> conveyorBeltsleftConBeltLS;
	static std::shared_ptr<frc::DigitalInput> conveyorBeltsrightConBeltLS;
	static std::shared_ptr<frc::SpeedController> conveyorBeltsleftConBeltSpeedController;
	static std::shared_ptr<frc::SpeedController> conveyorBeltsrightConBeltSpeedController;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
